### PR TITLE
Fix for issue #2

### LINKED ISSUE #2: Postman window not opening
Hello,

I am running Brackets Release 1.2 build 1.2.0-15697 (release 8f82e2a97). When I click on the extension icon, the postman window does not come up. I checked the demo and it just shows the postman window already open. Did I miss a menu item or something?

Thanks!

### PR DESCRIPTION
**Pull request by dsrw**
This fixes #2. Lodash 3.0 removed the data paramater from `_.template`.

https://github.com/lodash/lodash/wiki/Changelog#v300

### CODE REVIEW

**Comment by oleksbard** [comment]
Thanks for quick fix, but I cannot approve this Pull Request in it's state. Please see the comment above.

**Comment by dsrw** [comment]
Sorry, I don't quite follow. Do

**Comment by dsrw** [comment]
Sorry, I closed this by mistake.

Is 4f7ec5137a3807f43741fe1bbb062f35867ff7e6 what you want?

**Comment by oleksbard** [comment]
Yep, it is.

**Pull request merged**
